# adapted from https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - pip install . pytest-cov
# command to run tests
script:
  - PYTHONPATH=src pytest --cov
